title: Musings
author: JBBlunderbuss
email: j8blundell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of vague musings, possibly annoying.

# social links
# twitter_username: your-twitter-handle
github_username: JBBlunderbuss

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: JBBlunderbuss/jekyll-theme-console
